export default{
    capVideoUrl:"",//视频地址
    isshow:false,
    isshow2:false,
    isshow3:false,
    warnings4:[],//弹窗数据
    warnings3:[],
    warnings2:[],
    clRen:"孙伟菊",//处理人
    showInfo:{},
    type:"",//处理信息的类型
    warning4:null,//要处理的信息数据
    warning3:null,
    warning2:null,
    xqName:[],//小区名
    lgList:[],//楼号
    dyList:[],//单元名
    fjList:[],//具体房间信息
    url:"10.10.6.54",
    xqList:[],//小区列表
    isshow4:false,
    xqCode:"",//小区code
    limit:0,
    success:[],//弹窗信息
    err:[],
    bigPicIsshow:false,//大照片是否显示
    bigImgUrl:"",//照片地址
    name:"",//所选择的小区名
}